### ISSUE TITLE
Revise Enforcement Manual

### ISSUE THREAD

**Issue by karinlag** [carpentries/coc-guidelines-taskforce#2]
Draft a revised [enforcement manual](https://docs.google.com/document/d/1D4omrxOQRp8wZyLVr6obLpZafiHeLE6YYUMy9MsxJ5M/edit) in readable format. Be sure to track changes.

**Points to include:**

- [x] Ensure that staff pertinent staff are told about investigations
- [x] Ensure that instructors being investigated are not placed with new workshops or instructor training events
- [x] Discuss and decide to what extent the EC should have access, and how.
- [x] [Issues with CoC implementation](https://docs.google.com/document/d/1S_Jjh_kGaCqS9QUnzmlsKfACu3fo8yGNROUa8kTlhg0/edit)

**Comment by amyehodge** [comment]
As someone who is currently planning three workshops at my institution with local instructors and outside the help of the staff, I'm wondering if there is a way to let hosts like me know if there is someone they shouldn't be signing up to teach a workshop. I'm particularly concerned as I know there is a workshop going on at Stanford right now and hoping this incident isn't going on here. If it is and involves one of my local instructors, I'd like to know this, though of course not the details of the incident.

**Comment by karinlag** [comment]
@amyehodge I understand your concern here. However, I can't really see how we can do that without violating the privacy of the person being reported on. We are however taking steps to notify staff, and as long as a workshop is registered with us, I am presuming that they might be able to take steps if we should encounter such a situation.

That said, you are not part of the CoC. This repo is private for the CoC committee to ensure the confidentiality of both the reporter and the ones being reported on.  This repo should thus have been closed to you. I have asked staff to double check access, and to ensure that non-CoC members won't have access any longer.

**Comment by smcclatchy** [comment]
Hi Karin,

EC members have access to the CoC repo. I am receiving these as well and am keeping an eye on this situation. It’s important for EC members to know about these things as they are occurring.

Thanks,

Sue

JAX Data Science Study Group<http://smcclatchy.github.io/studyGroup/>
Study Group Code of Conduct<http://bit.ly/1VXIj2w>
#jaxdatascience

Sue McClatchy
Senior Program Manager, Bioinformatics Education
The Jackson Laboratory
207.288.6431

**Comment by amyehodge** [comment]
Thanks, @karinlag. I may have access because I am on the Exec Council, but if that's not appropriate, please do remove me. My concern above is that when notifying Carpentries about workshops we are not required to (and may not yet know) who will be teaching so the staff can't intervene. However, this would hopefully be a (very) rare occurrence.

**Comment by karinlag** [comment]
Oh, sorry, my bad! I don't have the list of people on the EC in my head, so apologies for not realizing who you were! (and yes, I am more than slightly embarrased now...)

Regarding memberships, I had interpreted things such that the EC would review things once in a while, but not be continously monitoring. This is a point we can discuss regarding the new enforcement manual.

Concerning workshops, you make a very good point. Maybe we should require people to register who will be teaching. I know that a lot is extracted from the workshop pages. Maybe we could extract information more than once... ? I don't know. We'd have to ask staff what is feasible and then figure out what is desireable.

**Comment by amyehodge** [comment]
No worries, @karinlag. And perhaps my thoughts are better elsewhere than here. Please do let me know.

**Comment by malvikasharan** [comment]
One way to avoid it could be that if a trainer wants to teach at a workshop (as an invited trainer), they should first contact the staff member (Sher and Maneehsa who are taking care of workshops). In that case, they can approve who is teaching. 

This will be advantageous also for facilitating a fair opportunity for the trainers who are interested in teaching at a workshop other than that they organize.

**Comment by swaldman3** [comment]
IMHO the EC should not all have access to this repo. By my understanding, keeping EC appraised of things as necessary is why we have an EC member on the CoC committee as liaison.

The greater the number of people who have access to ongoing CoC incidents, the greater the chance that somebody does not want to report an incident either because the person they wish to complain about can read it, or that because they think they have an ally who can read it.

If the EC (beyond the liaison) *are* to retain access here, then we need to update the new documents, where they explain who coc@carpentries.com goes to, to also note that the EC will be able to see ongoing discussions. If we're claiming that things are confidential, it's vital that we are clear about who they are confidential *to*. 

In the long run, as per Sage's advice, we also want to be moving to a platform that allows more granular access controls, to allow for a case where a member of CoC is complained about or otherwise needs to recuse themselves.

**Comment by quirksahern** [comment]
I don’t think the EC should have access either.

They only need to know if it is decided that there is an issue - and even then I don’t think they necessarily need to know the details of all issues.

If it’s serious or brings the Carpentries into disrepute, Yes. Otherwise, no. I’d struggle to justify it as legitimate interest given there is an EC liaison - potential breach of GDPR.

Sam


Sent from my iPhone

On 7 Sep 2018, at 23:09, Simon Waldman <notifications@github.com<mailto:notifications@github.com>> wrote:


IMHO the EC should not all have access to this repo. By my understanding, keeping EC appraised of things as necessary is why we have an EC member on the CoC committee as liaison.

The greater the number of people who have access to ongoing CoC incidents, the greater the chance that somebody does not want to report an incident either because the person they wish to complain about can read it, or that because they think they have an ally who can read it.

If the EC (beyond the liaison) are to retain access here then we need to update the new documents, where they explain who coc@carpentries.com<mailto:coc@carpentries.com> goes to, to also note that the EC will be able to see ongoing discussions. If we're claiming that things are confidential, it's vital that we are clear about who they are confidential to.

**Comment by karinlag** [comment]
The EC does not currently have access. We need to figure out if this is the way we want to proceed going forward. This issue will be part of the new Enforcement manual.

**Comment by kariljordan** [comment]
Someone submitted [this issue](https://github.com/carpentries/handbook/issues/267) to help with language in the enforcement manual.

**Comment by kariljordan** [comment]
Here is a thread from Maneesha, Tracy, and Erin about staff being made aware of CoC incidents. Let's consider these remarks when we begin to work on the enforcement manual.

> Maneesha: I very strongly believe *ALL* staff should be informed of all CoC violations.  We all interact with the community in different ways.  We can't have a staff member engaging a community member in a role while a CoC investigation is ongoing. I would also like to see the individual in question be informed there is an investigation about them.  This should be done in a way that we make it clear we want to hear from everyone what happened without immediately being accusatory.  Without this, from an instructor's point of view, they may be left wondering everytime something went even a little wrong, "was the a report filed on me?  what happened? why didn't anyone tell me?"  and it can harbor distrust.


> Erin: I agree that staff should be informed of CoC reports in cases where there is a reasonable chance that the reported violator will have interactions with staff members. There are cases (for example, issues with a learner at a workshop, or with a host) that not ALL staff need to be aware of. I would prefer to leave this to the judgement of the CoC committee, with the general guidance that they should be proactive about informing staff in cases where the reported violator is likely to interact with them. There is a delicate balance here between informing people who need to know, and respecting the privacy of the person who has been reported on. We could also recommend that the CoC staff liaison (who will know more than other CoC committee members be responsible for informing staff who need to know. I do not think the individual in question should be informed at the start of the investigation. In some cases, there is background research that the committee needs to do before entering into discussions with the reported party makes sense. They should not be required to contact the reported person until it makes sense for them to do so in the course of their investigation. 

> Tracy: Thanks for these thoughts. It's very important to respect privacy in CoC situations, so the any people involved outside of the CoC committee needs to be articulated in the policies and/or guidelines, so both reporters and reportees know who is notified. Limiting the number of people who are notified before an issue has been investigated is important for the privacy and confidence in the CoC process.  Could a structure of 'ED, AD and Program Coordinator will be notified if a CoC issue is reported. They can at their discretion and in coordination with the CoC committee notify other staff or workshop coordinators.' walk a line between privacy and notification if needed. Then if we are notified of an issue, we can do the work to see where in the community they are active and let people in those areas know if needed. This is outside the case of there being an ongoing issue that needs to be addressed immediately. In those cases there is already a process where the CoC can immediately engage any staff to handle an unsafe (on person or online) issue.

**Comment by kariljordan** [comment]
I am renaming this issue because it is a duplicate with #9 and I am closing #9.

**Comment by kariljordan** [comment]
All of these points have been addressed in the revised documentation, so closing this issue.
