### ISSUE TITLE
Request for Comments: Code of Conduct Incident Report Form

### ISSUE THREAD

**Issue by karinlag** [carpentries/coc-guidelines-taskforce#5]
>>update: The original form was created under The Carpentries organisation Typeform account. This means that all staff would have access to the results of this form. Because of that, I created a new form using **Google Forms**. The Typeform form was deleted.

[Here](https://goo.gl/forms/9qe1c5v4UytWPIxk1) is the draft incident report form. You can scroll down to view the questions without adding information. Please provide your feedback in this issue.

**Deadline: 17-February 2019**

> We should have a form that people and/or the CoC committee can fill out to gather necessary  information regarding an incidence. 
> 
> Note: at present this form is platform independent, how to gather info is a separate issue.
> 
> To be reviewed by policy when done.

**Comment by quirksahern** [comment]
Initial draft of incident data collection form - please let me know thoughts. Apologies for being a docx but isnt something I wanted to create using GoogleDocs

[CoCreportform.docx](https://github.com/carpentries/policy-actions/files/2159020/CoCreportform.docx)

**Comment by karinlag** [comment]
Thankyou for making this, this looks really good!

However, I started wondering about one thing while reading through this was that we might actually be in need of two different forms: one form that we use for taking a report in an ongoing situation, and one that summarizes the incident after it has been resolved.  The way this form stands right now, it to me read more like a post-incident report. In my mind I was thinking we could include some more specific guidelines for the report taker in this form. However, we then run the risk of "leading our witness" so to speak, so that part is not quite resolved for me yet.

And, we need to sort out a technical platform for this..

**Comment by quirksahern** [comment]
Was wondering if it should be split - initial response on reporting form, then a follow-up form with more detail of committee agreed action. If we give them IDs we could easily link the two documents.

**Comment by karinlag** [comment]
@quirksahern  I think that makes sense. We need to be able to track these things somehow anyhow, so giving each incident an id number is a good idea anyhow.

**Comment by kariljordan** [comment]
[Here](https://carpentries.typeform.com/to/s4VUdQ) is the draft incident report form. You can scroll down to view the questions without adding information. Please provide your feedback in this issue.

**Comment by karinlag** [comment]
I think this one contains most of the the info we need. Just a few questions:

What does "updates" mean in the first question? What effects does it have if someone says No here?

What if someone doesn't give a name and/or email address? I realized here that I have always assumed that we would be able to contact the reporter.

Last, a technical issue: we are now asking for a specific date/time, however, we might receive reports of something that wasn't just a single incident (harassment in an email exchange for instance). Should we (if technically possible) then allow people to state a time period?

**Comment by quirksahern** [comment]
Ditto @karinlag on timescale. Also is there a hard copy version that could be used at an event? 
Just thinking that in some instances people may want / need to write.

**Comment by kariljordan** [comment]
> [Here](https://carpentries.typeform.com/to/s4VUdQ) is the draft incident report form. You can scroll down to view the questions without adding information. Please provide your feedback in this issue.

Tagging @fmichonneau and @maneesha because I'll be discussing with them the feasibility of using this form.

**Comment by swaldman3** [comment]
"I realized here that I have always assumed that we would be able to contact the reporter." Pretty sure the CoC, or one of the related documents, specifically says that reports can be anonymous. Though this is obviously less useful.

"Please provide as much information as possible about the incident." should read "...as much information as you are comfortable giving...". 

What's the reason for having a form, rather than using email? I assume this is to try to prompt people to include the information that we'd like them to?

Thinking about things like the ranges of dates issue... I wonder if rather than a series of questions like this, it would be best to have just a free-text field where the default text, or some text next to it, gave a list of information that we'd ideally like?

IMHO we shouldn't be asking people to faff with forms at an event - we don't want CoC to become a paperwork burden, where instructors go "oh no, not a complaint, now I have to fill in forms". If they deal with an incident at an event, they can fill in the form afterwards. This does, however, highlight that the form needs to make sense when it's being filled in by somebody who isn't the person raising the complaint.

Some thought needs to go into the back-end used for this, who has access to the information, and so forth.

Sorry for the disjointed thoughts - no time this week!

**Comment by karinlag** [comment]
So, just to have things clear: as far as I've understood things we basically should consider moving away from using email for reporting. When people are reporting an incident, they are reporting it to the Carpentries. When we process that information we are doing it on behalf of the Carpentries. 

Now, when people give information to the Carpentries, it is then the responsibility of the Carpentries to make sure that that information is treated as it should. One of the big requirements there is that anybody in the community should be able to have their data deleted when they ask. The issue with us then using email for these things is that emails go into email accounts that the Carpentries can't control, thus it has no control over that information anymore.  This is why I am happy to see this form, because that means that the information can stay in one place, where we can go seek it out, instead of it being distributed to each of us individually. 

I also want to say that I second Simons other concerns regarding making sure that this is easy to fill out. We also need to ensure that the url is easy to figure out/find.

**Comment by swaldman3** [comment]
Understood - good point. Apologies if you had explained that before.

**Comment by karinlag** [comment]
@swaldman3 No problem, I am figuring out these things myself, and as a consequence my brain feels like a pretzel... :grinning:

**Comment by kariljordan** [comment]
The form includes a plugin such that when someone responds to it an email goes to the CoCc.

The following changes were also made to the form per feedback from @maneesha:

-Make sure the form receives a valid e-mail address from the reporter
**The only way to do this is to require an e-mail address, and we don't require they provide us one. We have to assume they will type in their email correctly.**

-Validate that the date is in the past
**Could not add validation that the date occurred in the past.**

-Don't want to put the reporter in the position of saying what the time is in UTC
**Changed so that we only ask for the date and time, not time zone**

-Auto-response and confirmation page should include comforting language
**[Here](https://docs.google.com/document/d/18GwkYPQXwjw5GeA3fQx7DhHd-Jw3dlPnNl_5_-HzzpA/edit) is a draft of the auto response**

-Intro description should link to the CoC and what will happen next and include comforting language.
**I included this in the auto response and intro language on the form.**

-Include link to workshop website or Carpentries event (not required)
**Added as optional**

[Here](https://goo.gl/forms/9qe1c5v4UytWPIxk1) is the revised form.

I'm particularly looking for feedback on the order of the questions.

**Comment by kariljordan** [comment]
All of the comments have been incorporated for the incident report form (the form someone fills out to report a potential CoC incident).

I converted @quirksahern's [incident report data form](https://docs.google.com/document/d/1FKR30JXU4yE7gsJa6SDQqwhWd8rUYKehy6NyMwwx7Mw/edit#heading=h.kplik45m4mox) (the form the incident response lead on the CoCc completes to compile the information about the incident, our meetings, and the resolution) to a Google document. This can also be used for in-person events if you all think that's necessary. We can put this in the README of our private repo. When an incident comes in, we'd just need to make a copy of this report and fill out the fields. This form and copies of it are only shared in the Google drive with the CoCc.

If you have comments or changes for the incident report data form, please make them directly in the [Google document](https://docs.google.com/document/d/1FKR30JXU4yE7gsJa6SDQqwhWd8rUYKehy6NyMwwx7Mw/edit#heading=h.kplik45m4mox).

I will close this issue.
